human_kinematics_publisher:
  ros__parameters:
    use_sim_time: false
    origin_frame: "world"
    camera_frame: "zed_left_camera_frame"
    configuration_topic_name: "body_configuration"
    param_topic_name: "body_parameters"
    keypoints_topic_name: "/zed/zed_node/body_trk/skeletons"